# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        
        self.glaph = PlotCanvas(None, width=5, height=4)
        navi = NavigationToolbar(self.glaph, self)

        
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.glaph, 0, 0, 1, 1)
        self.pushButton.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(400, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 298, 675))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 8, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 7, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_58.setObjectName("label_58")
        self.gridLayout_2.addWidget(self.label_58, 0, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_54.setObjectName("label_54")
        self.gridLayout_2.addWidget(self.label_54, 2, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_56.setObjectName("label_56")
        self.gridLayout_2.addWidget(self.label_56, 1, 3, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 8, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_2.addWidget(self.lineEdit_49, 0, 4, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_2.addWidget(self.lineEdit_56, 7, 4, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_2.addWidget(self.lineEdit_55, 6, 4, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 5, 3, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_2.addWidget(self.lineEdit_53, 4, 4, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_2.addWidget(self.lineEdit_52, 3, 4, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_2.addWidget(self.lineEdit_54, 5, 4, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 4, 3, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_2.addWidget(self.lineEdit_50, 1, 4, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_2.addWidget(self.lineEdit_51, 2, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 9, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 4, 2, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 9, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 8, 4, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 9, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 6, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 3, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 7, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 6, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 21))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTestes = QtWidgets.QAction(MainWindow)
        self.actionTestes.setObjectName("actionTestes")
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionTestes)
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.label_12.setText(_translate("MainWindow", "gT [mS]"))
        self.lineEdit_6.setText(_translate("MainWindow", "0.0205"))
        self.label_4.setText(_translate("MainWindow", "gNa [mS]"))
        self.lineEdit_2.setText(_translate("MainWindow", "1000"))
        self.label_8.setText(_translate("MainWindow", "gSyn [mS]"))
        self.lineEdit_4.setText(_translate("MainWindow", "56"))
        self.label_2.setText(_translate("MainWindow", "T [ms]"))
        self.lineEdit_3.setText(_translate("MainWindow", "-56.2"))
        self.label_6.setText(_translate("MainWindow", "gL [mS]"))
        self.label.setText(_translate("MainWindow", "N"))
        self.label_49.setText(_translate("MainWindow", "tau_max [ms]"))
        self.label_58.setText(_translate("MainWindow", "dt [ms]"))
        self.label_54.setText(_translate("MainWindow", "eNa [mV]"))
        self.label_56.setText(_translate("MainWindow", "Cm [uF]"))
        self.lineEdit_9.setText(_translate("MainWindow", "120"))
        self.lineEdit.setText(_translate("MainWindow", "1"))
        self.label_10.setText(_translate("MainWindow", "I_ext []"))
        self.label_9.setText(_translate("MainWindow", "eCa [mV]"))
        self.lineEdit_49.setText(_translate("MainWindow", "0.02"))
        self.lineEdit_56.setText(_translate("MainWindow", "608"))
        self.lineEdit_55.setText(_translate("MainWindow", "0"))
        self.label_51.setText(_translate("MainWindow", "gM [mS]"))
        self.lineEdit_53.setText(_translate("MainWindow", "-70.3"))
        self.lineEdit_52.setText(_translate("MainWindow", "-90"))
        self.lineEdit_54.setText(_translate("MainWindow", "0.075"))
        self.label_53.setText(_translate("MainWindow", "eL [mV]"))
        self.lineEdit_50.setText(_translate("MainWindow", "1"))
        self.lineEdit_51.setText(_translate("MainWindow", "50"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.lineEdit_5.setText(_translate("MainWindow", "6"))
        self.lineEdit_11.setText(_translate("MainWindow", "0.4"))
        self.lineEdit_10.setText(_translate("MainWindow", "0"))
        self.lineEdit_7.setText(_translate("MainWindow", "5.26"))
        self.label_52.setText(_translate("MainWindow", "eK [mV]"))
        self.lineEdit_8.setText(_translate("MainWindow", "0.025"))
        self.label_50.setText(_translate("MainWindow", "eSyn [mV]"))
        self.label_3.setText(_translate("MainWindow", "Vth [mV]"))
        self.label_7.setText(_translate("MainWindow", "tau_Syn [ms]"))
        self.label_5.setText(_translate("MainWindow", "gK [mS]"))
        self.menuTest.setTitle(_translate("MainWindow", "kanopero"))
        self.actionTestes.setText(_translate("MainWindow", "kashikoma"))
        
class PlotCanvas(FigureCanvas):

    def __init__(self, parent=None, width=10, height=8, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)

        FigureCanvas.__init__(self, fig)
        self.setParent(parent)

        FigureCanvas.setSizePolicy(self,
                                   QtWidgets.QSizePolicy.Expanding,
                                   QtWidgets.QSizePolicy.Expanding)
        FigureCanvas.updateGeometry(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

